<img src="https://cdn.analyticsvidhya.com/wp-content/uploads/2021/11/gg-fvdcgvc-01-1-scaled.webp" width="400">

# What is TensorFlow?

TensorFlow is an open-source Python library developed for Artificial Intelligence (AI) and Deep Learning.

It helps computers learn from data and make predictions without being explicitly programmed for every task.

Using TensorFlow, we can:

✔ Build Deep Learning Models

✔ Train Neural Networks

✔ Image Recognition

✔ Face Recognition

✔ Speech Recognition

✔ Language Translation

✔ Recommendation Systems

✔ Time Series Prediction

TensorFlow is one of the world's most popular Deep Learning libraries.

# History of TensorFlow

📅 First Released:
2015

🏢 Developed By:
Google Brain Team

TensorFlow was developed by the Google Brain team to make Artificial Intelligence and Machine Learning research easier.

It replaced Google's earlier deep learning system called DistBelief and was later released as open-source software.

Today, TensorFlow is widely used in AI research, industries, and universities.

# Why was TensorFlow Created?

Traditional Machine Learning works well for many tasks, but complex problems such as image recognition, speech recognition, and natural language processing require Deep Learning.

TensorFlow was created to:

✔ Build Neural Networks

✔ Train Deep Learning Models

✔ Handle Large Datasets

✔ Run on CPUs, GPUs, and TPUs

✔ Develop AI Applications Faster

# Features of TensorFlow

✔ Open Source

✔ Easy to Build Neural Networks

✔ Supports CPUs, GPUs, and TPUs

✔ Fast Training

✔ Keras API Integration

✔ TensorBoard Visualization

✔ Cross Platform

✔ Production Ready

✔ Large Community Support

<img src="https://images.openai.com/static-rsc-4/Cj8uTEbDxgFAUpuwbalAs0pAYkuWDAA-vc8wCNrYKPTbGXdbYXWudPH1troGrELbCD9Gin8JAyBUQf1D5AKIlfIGEh_D9e8HVmf9CVV_XTpcBercJFUfKtS5Zmt-VJOaMS6SHlekQp-INUzo_Rn2xfl31TsEnFildEbc73nKBS0y65KSm4PU83CKzQYPlCzn?purpose=fullsize" width="800">

# Install TensorFlow

In [ ]:
# Install TensorFlow

!pip install tensorflow

# Import TensorFlow

In [ ]:
# Import TensorFlow

import tensorflow as tf

# Create a Constant Tensor

In [ ]:
import tensorflow as tf

tensor = tf.constant([10,20,30])           # creates immutable tensor

print(tensor)

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


# Create a Variable

In [ ]:
var = tf.Variable([5,10,15])

print(var)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 5, 10, 15], dtype=int32)>


# Tensor Shape

In [ ]:
print(tensor.shape)

(3,)


# Tensor Data Type

In [ ]:
print(tensor.dtype)

<dtype: 'int32'>


# Tensor Addition

In [ ]:
a = tf.constant([1,2,3])

b = tf.constant([4,5,6])

print(tf.add(a,b))

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


# Tensor Multiplication

In [ ]:
print(tf.multiply(a,b))

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


# Matrix Multiplication

In [ ]:
A = tf.constant([[1,2],[3,4]])

B = tf.constant([[5,6],[7,8]])

print(tf.matmul(A,B))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


# Random Tensor

In [ ]:
random_tensor = tf.random.uniform((2,3))

print(random_tensor)

tf.Tensor(
[[0.08524275 0.17955601 0.0996238 ]
 [0.1204927  0.22920346 0.3650856 ]], shape=(2, 3), dtype=float32)


# Reshape Tensor

In [ ]:
tensor = tf.constant([1,2,3,4,5,6])

print(tf.reshape(tensor,(2,3)))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


# Convert NumPy to Tensor

In [ ]:
import numpy as np

arr = np.array([1,2,3])

tensor = tf.convert_to_tensor(arr)

print(tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


# Convert Tensor to NumPy

In [ ]:
print(tensor.numpy())

[1 2 3]


# Sequential Model

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(1)
])

print(model)

<Sequential name=sequential, built=False>


# Compile Model

In [ ]:
model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["accuracy"]
)

# Train Model

In [ ]:
# Example only
# model.fit(X_train, y_train, epochs=10)       # Trains the model using training data.

# Evaluate Model

In [ ]:
# model.evaluate(X_test, y_test)

# Make Predictions

In [ ]:
# predictions = model.predict(X_test)

# Save Model

In [ ]:
model.save("my_model.keras")

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_api.py:107: UserWarning: You are saving a model that has not yet been built. It might not contain any weights yet. Consider building the model first by calling it on some data.
  return saving_lib.save_model(model, filepath)


# Useful Modules

tf.keras

tf.keras.layers

tf.keras.models

tf.keras.optimizers

tf.keras.losses

tf.keras.metrics

tf.data

tf.image

tf.random

tf.math

tf.nn

tf.io

tf.saved_model

# Useful Functions

tf.constant()

tf.Variable()

tf.reshape()

tf.matmul()

tf.add()

tf.multiply()

tf.random.uniform()

tf.convert_to_tensor()

tf.keras.Sequential()

Dense()

compile()

fit()

evaluate()

predict()

save()

load_model()

# Summary

TensorFlow is one of the world's leading libraries for Artificial Intelligence and Deep Learning.

It provides tools to create, train, evaluate, and deploy neural networks for solving real-world problems.

Learning TensorFlow after NumPy, Pandas, Matplotlib, Seaborn, and Scikit-learn is a major step toward becoming an AI Engineer, Machine Learning Engineer, or Deep Learning Engineer.