<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIlIfVHvYT4D-Z9Ah0u3mvgiUfPVvxX1fu2vp9fmo1wg&s=10" width="400">

# What is PyTorch?

PyTorch is an open-source Python library used for Artificial Intelligence (AI), Machine Learning (ML), and Deep Learning (DL).

It helps developers build and train neural networks for solving complex problems.

Using PyTorch, we can:

✔ Build Deep Learning Models

✔ Image Classification

✔ Object Detection

✔ Natural Language Processing (NLP)

✔ Speech Recognition

✔ Chatbots

✔ Recommendation Systems

✔ Robotics

PyTorch is widely used in research and industry because it is flexible and easy to debug.

# History of PyTorch

📅 First Released:
2016

🏢 Developed By:
Facebook AI Research (FAIR)

👨 Main Contributors:
Adam Paszke and the Facebook AI Research team

PyTorch was developed to make Deep Learning easier and more flexible.

Today, it is maintained by the PyTorch Foundation under the Linux Foundation and is used by researchers, universities, and technology companies around the world.

# Why was PyTorch Created?

Earlier Deep Learning frameworks were powerful but often difficult to debug and experiment with.

PyTorch was created to provide:

✔ Easy model building

✔ Dynamic computation graphs

✔ Faster research and experimentation

✔ GPU acceleration

✔ Better debugging using normal Python code

# Features of PyTorch

✔ Open Source

✔ Beginner Friendly

✔ Dynamic Computation Graph

✔ GPU Support

✔ Automatic Differentiation (Autograd)

✔ Large Community

✔ Easy Debugging

✔ Fast Training

✔ Cross Platform

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/01_a_pytorch_workflow.png" width="700">

# Install PyTorch

In [ ]:
# Install PyTorch

!pip install torch torchvision torchaudio

# Import PyTorch

In [ ]:
# Import PyTorch

import torch          # torch is the main package of PyTorch.

# Create a Tensor

In [ ]:
import torch

tensor = torch.tensor([10,20,30])        # Creates a Pytorch tensor

print(tensor)

tensor([10, 20, 30])


# Tensor Shape

In [ ]:
print(tensor.shape)

torch.Size([3])


# Tensor Data Type

In [ ]:
print(tensor.dtype)

torch.int64


# Create Zeros Tensor

In [ ]:
tensor = torch.zeros((2,3))

print(tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Create Ones Tensor

In [ ]:
tensor = torch.ones((2,3))

print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


# Random Tensor

In [ ]:
tensor = torch.rand((2,3))

print(tensor)

tensor([[0.8134, 0.7180, 0.0156],
        [0.8624, 0.5457, 0.6126]])


# Tensor Addition

In [ ]:
a = torch.tensor([1,2,3])

b = torch.tensor([4,5,6])

print(a+b)

tensor([5, 7, 9])


# Tensor Multiplication

In [ ]:
print(a*b)

tensor([ 4, 10, 18])


# Matrix Multiplication

In [ ]:
A = torch.tensor([[1,2],[3,4]])

B = torch.tensor([[5,6],[7,8]])

print(torch.matmul(A,B))

tensor([[19, 22],
        [43, 50]])


# Reshape Tensor

In [ ]:
tensor = torch.arange(6)

print(tensor.reshape(2,3))

tensor([[0, 1, 2],
        [3, 4, 5]])


# Convert NumPy Array to Tensor

In [ ]:
import numpy as np

arr = np.array([1,2,3])

tensor = torch.from_numpy(arr)

print(tensor)

tensor([1, 2, 3])


# Convert Tensor to NumPy

In [ ]:
print(tensor.numpy())

[1 2 3]


# Check GPU Availability

In [ ]:
print(torch.cuda.is_available())  # Returns True if a CUDA-compatible GPU is available.

False


# Move Tensor to GPU

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tensor = tensor.to(device)

print(tensor)

tensor([1, 2, 3])


# Create a Neural Network

In [ ]:
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(4,16),
    nn.ReLU(),
    nn.Linear(16,3)
)

print(model)

Sequential(
  (0): Linear(in_features=4, out_features=16, bias=True)
  (1): ReLU()
  (2): Linear(in_features=16, out_features=3, bias=True)
)


# Loss Function

In [ ]:
criterion = nn.CrossEntropyLoss()

# Optimizer

In [ ]:
import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=0.001)

# Forward Pass

In [ ]:
x = torch.rand((1,4))

output = model(x)

print(output)

tensor([[-0.4124,  0.1395,  0.2629]], grad_fn=<AddmmBackward0>)


# Save Model

In [ ]:
# torch.save(model.state_dict(),"model.pth")

# Load Model

In [ ]:
# model.load_state_dict(torch.load("model.pth"))

# Useful Modules

torch

torch.nn

torch.optim

torch.cuda

torch.utils.data

torchvision

torchaudio

torch.autograd

torch.nn.functional

# Useful Functions

torch.tensor()

torch.zeros()

torch.ones()

torch.rand()

torch.arange()

reshape()

torch.matmul()

torch.from_numpy()

numpy()

cuda.is_available()

device()

Sequential()

Linear()

ReLU()

CrossEntropyLoss()

Adam()

save()

load()

# Summary

PyTorch is one of the world's most popular Deep Learning libraries.

It provides flexible tools to build, train, and deploy neural networks for AI applications.

Learning PyTorch after NumPy, Pandas, Matplotlib, Seaborn, Scikit-learn, TensorFlow, and Keras prepares you for advanced Machine Learning, Deep Learning, and AI development.